// Documentation Category Icons
export { default as APIGuidesIcon } from './api-guides-icon'
export { default as APIReferenceIcon } from './api-reference-icon'
export { default as AppDevelopmentIcon } from './app-development-icon'
export { default as ReleaseNotesIcon } from './release-notes-icon'
export { default as StorefrontDevelopmentIcon } from './storefront-development-icon'
export { default as TroubleshootingIcon } from './troubleshooting-icon'
export { default as GearTroubleshootingIcon } from './gear-troubleshooting-icon'
export { default as VTEXIOAppsIcon } from './vtex-io-apps-icon'
export { default as DocumentationUpdatesIcon } from './documentation-updates-icon'
export { default as HelpCenterIcon } from './helpcenter-icon'
export { default as DeveloperPortalIcon } from './developer-portal-icon'
export { default as FAQIcon } from './faq-icon'
export { default as KnownIssuesIcon } from './known-issues-icon'
export { default as MegaphoneIcon } from './megaphone-icon'
export { default as GraphIcon } from './graph-icon'
export { default as WarningIcon } from './warning-icon'
export { default as PaperIcon } from './paper-icon'
export { default as StartHereIcon } from './start-here-icon'
export { default as TutorialsIcon } from './tutorials-icon'
export { default as AnnouncementIcon } from './announcement-icon'
export { default as VTEXDevPortalIcon } from './vtex-devportal-icon'
export { default as VTEXHelpCenterIcon } from './vtex-helpcenter-icon'

// Status/Change Icons
export { default as AddedIcon } from './added-icon'
export { default as DeprecatedIcon } from './deprecated-icon'
export { default as FixedIcon } from './fixed-icon'
export { default as ImprovedIcon } from './improved-icon'
export { default as RemovedIcon } from './removed-icon'
export { default as InfoIcon } from './info-icon'
export { default as NewIcon } from './new-icon'

// Social Media & Sharing Icons
export { default as EmailIcon } from './email-icon'
export { default as FacebookIcon } from './facebook-icon'
export { default as LinkedinIcon } from './linkedin-icon'
export { default as LinkIcon } from './link-icon'
export { default as ShareIcon } from './share-icon'
export { default as TwitterIcon } from './twitter-icon'
export { default as GithubIcon } from './github-icon'
export { default as CommunityIcon } from './community-icon'
export { default as FacebookCircleIcon } from './facebook-circle-icon'
export { default as LinkedinCircleIcon } from './linkedin-circle-icon'
export { default as TwitterCircleIcon } from './twitter-circle-icon'
export { default as YoutubeIcon } from './youtube-icon'
export { default as InstagramIcon } from './instagram-icon'
export { default as ChatGPTIcon } from './chatgpt-icon'
export { default as ClaudeIcon } from './claude-icon'
export { default as GeminiIcon } from './gemini-icon'
export { default as CopilotIcon } from './copilot-icon'

// UI Action Icons
export { default as CloseFilterIcon } from './close-filter-icon'
export { default as CloseIcon } from './close-icon'
export { default as CopyIcon } from './copy-icon'
export { default as EditIcon } from './edit-icon'
export { default as ExpandedResultsIcon } from './expanded-results-icon'
export { default as SearchIcon } from './search-icon'
export { default as SideBarToggleIcon } from './sidebar-toggle-icon'
export { default as GridIcon } from './grid-icon'
export { default as TrashcanIcon } from './trashcan-icon'
export { default as FilterIcon } from './filter-icon'
export { default as MenuIcon } from './menu-icon'
export { default as CheckboxIcon } from './checkbox'
export { default as ResizeIcon } from './resize-icon'

// Navigation Icons
export { default as ArrowLeftIcon } from './arrow-left-icon'
export { default as ArrowRightIcon } from './arrow-right-icon'
export { default as CaretIcon } from './caret'
export { default as LongArrowIcon } from './long-arrow-icon'
export { default as VTEXLogoFooter } from './vtex-logo-footer'

// Feedback Icons
export { default as LikeIcon } from './like-icon'
export { default as LikeSelectedIcon } from './like-selected-icon'
